---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/k8s-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  storageClassName: manual
  volumeName: local-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-pvc
  template:
    metadata:
      labels:
        app: data-exchange-pvc
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
          - /bin/sh
          - -c
        args:
          - |
            while true
            do
              date >> /shared/data.txt
              sleep 5
            done
        volumeMounts:
        - mountPath: /shared
          name: data

      - name: multitool
        image: wbitt/network-multitool
        command:
          - /bin/sh
          - -c
        args:
          - tail -f /shared/data.txt
        volumeMounts:
        - mountPath: /shared
          name: data

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: local-pvc
